### PR TITLE
Updating REST and GraphQL schema for cookies field, adding rs052 error markdown

### PR DESCRIPTION
**Pull request by DerekSiemens**
REST API Swagger Schema: Updating user upsert schema to include cookies field
GraphQL Schema: Adding cookies field to UserInput Type

Creating the markdown for the new cookie related error, rs052

## Types of changes

- [x] Documentation content
- [ ] Page Layout / templates / structure
- [ ] Internal / code cleanup / build system

### CODE REVIEW

**Review by loganvolkers — DISMISSED** [review]
Looks good.

Definitely a reminder for @johanventer and @slisaasquatch that we should centralize the schema for the Rest and GraphQL API.

**Review by loganvolkers — CHANGES_REQUESTED** [review]
@DerekSiemens please confirm with @slisaasquatch, but I believe both the `POST` and `PUT` for user create/upsert should both accept `cookies`.

Currently this method doesn't have it: https://deploy-preview-115--saasquatch-docs.netlify.app/api/methods/#open_create_user

**Comment by DerekSiemens** [comment]
Should be good now! @loganvolkers

**Review by loganvolkers — APPROVED** [review]
Looks good.

**Pull request merged**
